namespace: prod-wordpress
secretGenerator:
- name: mysql-host
  literals:
  - db-host=prod-wordpress-mysql
  behavior: replace
- name: mysql-db
  literals:
  - database=wordpress
  behavior: replace
- name: mysql-usr
  literals:
  - user=wordpress
  behavior: replace
- name: mysql-pass
  literals:
  - password=Y3fuvUgqz9aSJmGaEa
  behavior: replace
bases:
- ../../base
namePrefix: prod-
patchesStrategicMerge:
- mysql-deployment.yaml
- wordpress-deployment.yaml
- wordpress-ingressroute.yaml
- wordpress-headers.yaml
images:
- name: mysql
  newName: mysql
  newTag: 8.0.27
- name: wordpress
  newName: wordpress
  newTag: 5.8.2-apache
