namespace: prod-wordpress
secretGenerator:
- name: mysql-host
  literals:
  - db-host=prod-wordpress-mysql
  behavior: replace
- name: mysql-db
  literals:
  - database=wordpress
  behavior: replace
- name: mysql-usr
  literals:
  - user=wordpress
  behavior: replace
- name: mysql-pass
  literals:
  - password=SgUV52ctS6HorysXprfg
  behavior: replace
bases:
- ../../base
namePrefix: prod-
patchesStrategicMerge:
- mysql-deployment.yaml
- wordpress-deployment.yaml
- wordpress-ingressroute.yaml
